### ISSUE TITLE
evt.getCursorPosition() throws an error with Bing Maps and Marker

### ISSUE THREAD

**Issue by SwanMougnoz** [markkr125/jsmaps#1]
It seems that when attanching an event handler (in my case "dragend" or "position_changed") to a marker on Bing map the function getCursorPosition() fails to retrieve the actual position and throws an error : "Uncaught TypeError: e.getX is not a function"

Here is my code :

`jsMaps.api.attach_event(markerInstance, 'position_changed', function(evt) {
     console.log(evt.getCursorPosition());
});`

I can still use markerInstance.getPosition() but I think it was worth to notice this.
Regard :)

**Comment by markkr125** [comment]
Fixed
