### ISSUE TITLE
jsMaps.api.removeEvent not working with native map supplier

### ISSUE THREAD

**Issue by SwanMougnoz** [markkr125/jsmaps#2]
Hello, 

I noticed that the removeEvent method from the api were not working when using a native map. I searched what cause this issue in the code and noticed that the final call to removeEventListener were not referencing any event handler : file core.native-helper.js line 302

`jsMaps.Native.Event.remove = function (element,eventTrigger) {
    element.removeEventListener(eventTrigger, function () {});
};`

I will try to fix this but I would want to know if there is a reason why this has not been implemented ?
Thank

**Comment by markkr125** [comment]
A misunderstanding on how js events works, sorry about that.
